/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Detail: typeof import('./src/components/Detail/index.vue')['default']
    DetailPost: typeof import('./src/components/Detail/DetailPost.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Guide: typeof import('./src/components/Guide/index.vue')['default']
    GuideItem: typeof import('./src/components/Guide/GuideItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PostDetail: typeof import('./src/components/Detail/PostDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
